2024-01-22 18:03:17 - ERROR - Cannot save file into a non-existent directory: 'XX.data/repob:main'
2024-01-22 18:03:17 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 376, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 67, in load_previous_results
    commits_analyzed_dataframe.to_csv(commits_analyzed, index=False)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'XX.data/repob:main'

2024-01-22 18:03:17 - ERROR - Cannot save file into a non-existent directory: 'XX.data/repob:main'
2024-01-22 18:03:17 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 376, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 67, in load_previous_results
    commits_analyzed_dataframe.to_csv(commits_analyzed, index=False)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'XX.data/repob:main'

2024-01-22 19:07:57 - ERROR - /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpqtsty8uu/.temp/https:__github.com_example_repo.git
2024-01-22 19:07:57 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/coupling/logical_coupling.py", line 375, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/coupling/logical_coupling.py", line 39, in load_previous_results
    checkout(path_to_repo, branch, logger)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/coupling/util.py", line 19, in checkout
    repo = Repo(path_to_repo)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpqtsty8uu/.temp/https:__github.com_example_repo.git

2024-01-22 19:07:57 - ERROR - /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpspc35llp/.temp/https:__github.com_example_repo.git
2024-01-22 19:07:57 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/coupling/logical_coupling.py", line 375, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/coupling/logical_coupling.py", line 39, in load_previous_results
    checkout(path_to_repo, branch, logger)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/coupling/util.py", line 19, in checkout
    repo = Repo(path_to_repo)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpspc35llp/.temp/https:__github.com_example_repo.git

