2024-01-22 13:35:39 - ERROR - Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/example/repo.git .temp/https:__github.com_example_repo.git
  stderr: 'Cloning into '.temp/https:__github.com_example_repo.git'...
remote: Repository not found.
fatal: repository 'https://github.com/example/repo.git/' not found
'
2024-01-22 13:35:39 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 367, in run
    path_to_cloned_repo = clone(repo_url)
                          ^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/util.py", line 12, in clone
    Repo.clone_from(repo_url, path)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 1328, in clone_from
    return cls._clone(
           ^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 1237, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/util.py", line 453, in finalize_process
    proc.wait(**kwargs)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/example/repo.git .temp/https:__github.com_example_repo.git
  stderr: 'Cloning into '.temp/https:__github.com_example_repo.git'...
remote: Repository not found.
fatal: repository 'https://github.com/example/repo.git/' not found
'

2024-01-22 13:51:44 - ERROR - /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpfd_dtp09/.temp/https:__github.com_example_repo.git
2024-01-22 13:51:44 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 373, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 39, in load_previous_results
    checkout(path_to_repo, branch, logger)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/util.py", line 19, in checkout
    repo = Repo(path_to_repo)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpfd_dtp09/.temp/https:__github.com_example_repo.git

2024-01-22 13:53:23 - ERROR - /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmplfu5em7c/.temp/https:__github.com_example_repo.git
2024-01-22 13:53:23 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 373, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 39, in load_previous_results
    checkout(path_to_repo, branch, logger)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/util.py", line 19, in checkout
    repo = Repo(path_to_repo)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmplfu5em7c/.temp/https:__github.com_example_repo.git

2024-01-22 13:58:32 - ERROR - /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpg2vt6l1f/.temp/https:__github.com_example_repo.git
2024-01-22 13:58:32 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 373, in run
    data, components_to_ignore, commits_analyzed = load_previous_results(repo_name, path_to_cloned_repo, branch)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 39, in load_previous_results
    checkout(path_to_repo, branch, logger)
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/util.py", line 19, in checkout
    repo = Repo(path_to_repo)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpg2vt6l1f/.temp/https:__github.com_example_repo.git

2024-01-22 14:10:05 - ERROR - /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpsp7fqq5i/.temp/https:__github.com_example_repo.git
2024-01-22 14:10:05 - ERROR - Traceback (most recent call last):
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 388, in run
    new_data, new_commits_analyzed = analyze_commits(path_to_cloned_repo, branch, commit_hash, last_commit,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/LogicalCouplingNoDb/src/logical_coupling.py", line 128, in analyze_commits
    for commit in repository.traverse_commits():
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pydriller/repository.py", line 215, in traverse_commits
    with self._prep_repo(path_repo=path_repo) as git:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pydriller/repository.py", line 186, in _prep_repo
    self.git = Git(local_path_repo, self._conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pydriller/git.py", line 61, in __init__
    self._open_repository()
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/pydriller/git.py", line 87, in _open_repository
    self._repo = Repo(str(self.path))
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncdaam/PycharmProjects/LogicalCouplingTool/.venv/lib/python3.11/site-packages/git/repo/base.py", line 215, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /private/var/folders/k1/23kw474556dc5nt9ghkdmqfm848fbh/T/tmpsp7fqq5i/.temp/https:__github.com_example_repo.git

